### ISSUE TITLE
Error in legal expression with anchor

### ISSUE THREAD

**Issue by theHamsta** [tree-sitter-grammars/tree-sitter-query#26]
```
(function_declaration
  (import_path
    ((identifier) @function .)))
```

@clason @amaanq could this be the reason why Topiary formatting has problems with some anchor expressions

```
named_node [0, 0] - [2, 32]
  name: identifier [0, 1] - [0, 21]
  named_node [1, 2] - [2, 31]
    name: identifier [1, 3] - [1, 14]
    grouping [2, 4] - [2, 30]
      named_node [2, 5] - [2, 27]
        name: identifier [2, 6] - [2, 16]
        capture [2, 18] - [2, 27]
          name: identifier [2, 19] - [2, 27]
      ERROR [2, 28] - [2, 29]
```

**Comment by clason** [comment]
Topiary is handling anchors correctly; it's query-fmt that mangles them (due to lack of explicit handling).

**Comment by clason** [comment]
Is that even valid (trailing anchor)?

**Comment by theHamsta** [comment]
> Is that even valid (trailing anchor)?

It should be. It means the last named node of a parent

**Comment by theHamsta** [comment]
![grafik](https://github.com/nvim-treesitter/tree-sitter-query/assets/7189118/29dc3be8-a0ac-4dfc-9339-ff0a5f5d445c)

**Comment by clason** [comment]
Do we need to explicitly add an anchor to
https://github.com/nvim-treesitter/tree-sitter-query/blob/3a9808b22742d5bd906ef5d1a562f2f1ae57406d/grammar.js#L77-L83

(Maybe as a new named node?)
