### ISSUE TITLE
feature: recorgnize super-type/concrete type syntax

### ISSUE THREAD

**Issue by theHamsta** [tree-sitter-grammars/tree-sitter-query#29]
### Did you check the tree-sitter docs?

- [ ] I have read all the [tree-sitter docs](https://tree-sitter.github.io/tree-sitter/using-parsers) if it relates to using the parser

### Is your feature request related to a problem? Please describe.

Tree-sitter supports this wild syntax

https://github.com/tree-sitter/tree-sitter-javascript/blob/9802cc5812a19cd28168076af36e88b463dd3a18/queries/locals.scm#L15
as parsed here https://github.com/tree-sitter/tree-sitter/blob/b6c75ccec166792c65648026b76a10c098060d97/lib/src/query.c#L2349. Should we support it in the parser? Or is it too rarely used (only one known occurrence)

### Describe the solution you'd like

Add a rule for supertype/concrete type syntax

### Describe alternatives you've considered

Just ignore this syntax as if it not existed (would be totally ok for me)

**Comment by clason** [comment]
>  (only one known occurrence)

Now there are two ;) (Haskell highlights)

The question is _how_ we want to support this:
1. just not break (that's what #33 does), or
2. actually expose these as different (nested?) nodes.
