### ISSUE TITLE
feature: regex injection for #match? predicate

### ISSUE THREAD

**Issue by znd4** [tree-sitter-grammars/tree-sitter-query#31]
### Did you check the tree-sitter docs?

- [x] I have read all the [tree-sitter docs](https://tree-sitter.github.io/tree-sitter/using-parsers) if it relates to using the parser

### Is your feature request related to a problem? Please describe.

authoring regular expressions is a pain

### Describe the solution you'd like

It'd be nice to have pretty tree-sitter-regex higlighting when I'm editing a `#match?` predicate

### Describe alternatives you've considered

I tried this query, but the `#offset!` doesn't seem to be working:

```scm
(predicate
  name: (identifier) @match
  (#eq? @match "match")
  parameters: (parameters
    (string) @injection.content
    (#offset! @injection.content 1 0 -1 0)
    (#set! injection.language "regex")
  )
)
```

### Additional context

I'm using neovim

**Comment by clason** [comment]
This is a Neovim issue with predicates and multiple matches; nothing that can be fixed here.
