### ISSUE TITLE
feature: Any chance you'll publish it on PyPI?

### ISSUE THREAD

**Issue by 8day** [tree-sitter-grammars/tree-sitter-query#40]
### Did you check the tree-sitter docs?

- [X] I have read all the [tree-sitter docs](https://tree-sitter.github.io/tree-sitter/using-parsers) if it relates to using the parser

### Is your feature request related to a problem? Please describe.

n/a

### Describe the solution you'd like

n/a

### Describe alternatives you've considered

It doesn't seem like it's present on PyPI. At least it's not published by ObserverOfTime or amaanq, who published other most common languages.

### Additional context

n/a

**Comment by clason** [comment]
Eventually we will publish all grammars on all relevant registries, but we are waiting for upstream (tree-sitter) changes that will make this much easier and more consistent.

**Comment by ObserverOfTime** [comment]
In the meantime you can `pip install git+https://github.com/tree-sitter-grammars/tree-sitter-query`
